version: "2.4"
services:
  mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql/sql-scripts/:/docker-entrypoint-initdb.d/

  db-checker:
    image: malinthaprasan/db-checker-tomcat:1.1
    environment:
      - TOMCAT_JDBC_URL=jdbc:mysql://mysql:3306/choreo_apim_db?useSSL=false
      - TOMCAT_JDBC_PASSWORD=root
      - TOMCAT_JDBC_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - TOMCAT_JDBC_USERNAME=root
      - TOMCAT_JDBC_INITIAL_SIZE=10
      - TOMCAT_JDBC_MIN_IDLE=10
      - TOMCAT_JDBC_MAX_IDLE=10
      - TOMCAT_JDBC_MAX_ACTIVE=100
      - TOMCAT_JDBC_MAX_AGE=43200000
      - TOMCAT_JDBC_VALIDATION_QUERY=SELECT 1
      - TOMCAT_JDBC_LOG_ABANDONED=true
      - TOMCAT_JDBC_VALIDATION_INTERVAL=30000
      - TOMCAT_JDBC_DEFAULT_AUTOCOMMIT=true
      - TOMCAT_JDBC_REMOVE_ABANDONED=true
      - TOMCAT_JDBC_JDBC_INTERCEPTORS=SlowQueryReport(threshold=1000)
      - TOMCAT_JDBC_REMOVE_ABANDONED_TIMEOUT=180
      - TOMCAT_JDBC_VALIDATION_QUERY_TIMEOUT=2
      - TOMCAT_JDBC_TEST_ON_BURROW=true
      - TOMCAT_JDBC_TEST_WHILE_IDLE=true
      - TOMCAT_JDBC_MAX_WAIT=60000
      - DB_CHECKER_TOTAL_ITERATIONS=-1
      - DB_CHECKER_ITERATIONS_PER_CONNECTION=5
      - DB_CHECKER_SLEEP_TIME_MS=5000
      - DB_CHECKER_QUERY=SELECT API_NAME FROM AM_API
      - DB_CHECKER_ITERATE_RESULT_SET=true
      - DB_CHECKER_LOG_RESULT_SET=true
    depends_on:
      mysql:
        condition: service_healthy